### ISSUE TITLE
Application Method

### ISSUE THREAD

**Issue by ljkimmel** [hobovirtual/vrealize-cm#1]
Could you explain your architectural approach on this? For the most part you seem to be creating a workflow for each individual control. Each workflow contains static attributes for the key and value which are then passed to a common workflow that validates and applies the setting. It seems to me that you could use a configuration element to store all of the key-value pairs, retrieve the element and values in a scriptable task, and then use a foreach workflow element (tied to the common workflow) to apply each value. Did you consider that approach? If not, can you share your reasoning? Good work, though. I'm definitely using the main workflow and associated functions.

**Comment by hobovirtual** [comment]
Hi @ljkimmel 

You're right and this is what i did when the vRO MP 3.0 was released :) 

You can find the recent versions here

[Virtual Machines](https://code.vmware.com/samples/5800/self-driving-operations---vsphere-security-guide---virtual-machines---vro-mp-3.0?h=Sample
)
[Network](https://code.vmware.com/samples/5731/self-driving-operations---vsphere-security-guide---network---vro-mp-3.0?h=Sample)

In the 3.0 MP there's also some samples that were provided by John Dias which can be used.

Hope this helps

**Comment by hobovirtual** [comment]
Thanks to @ljkimmel for finding that the alert definition were not in the vRO MP 3.0 version on code.vmware.com 

Package was updated and uploaded to the code.vmware.com site
